// Every word the page shows, in English and Chinese. Data values (pains, sources, ids, error text from
// the backend) never pass through here. `{name}` is filled from t()'s second argument.
const en = {
  title: 'Harness RSI', subtitle: 'Pick what to build next. Nothing runs until you decide.',
  demoNote: 'Demo mode: sample data from the fixtures. Nothing is saved. Remove ?demo=1 from the address to see your data.',
  tabsAria: 'Harness RSI sections', tab_settings: 'Settings',
  statProposals: 'Proposals', statPending: 'Waiting for you', statSignals: 'Signals', statPrompts: 'Prompt changes',
  loadFailed: 'Could not load data', emptyHint: 'Run a round, or open this page with ?demo=1 to preview sample data.',
  noSignals: 'No signals yet', noRuns: 'No scheduled runs yet',
  heat: '{people} people / {days} days', cost: '{files} files · {lines} lines',
  scoreJudge: 'Judge: base {base} → head {head}', scoreNot: 'Not scored: {note}', scoreYet: 'Not scored yet',
  judge_pass: 'pass', judge_fail: 'fail', state_merged: 'merged', state_open: 'open', state_closed: 'closed',
  regressNotRun: 'Regress: not run yet', regressLine: 'Regress @ {sha}: {pass}/{n} pass', regressLineBad: 'Regress @ {sha}: {pass}/{n} pass · {bad} regression(s)',
  dec_do: 'Do', dec_skip: 'Skip', dec_later: 'Later',
  savedDecision: 'Saved: {d}', decideFailed: 'Could not save the decision: {e}',
  dispOpening: 'Opening a worker chat…', dispChat: 'Worker chat: {s}',
  savedNotStarted: 'Saved. Not started: start its worker chat in Needs you, or turn on auto-dispatch.',
  dispStarted: 'Started.', dispAlready: 'Already dispatched.', dispAlreadyOpening: 'Already dispatched: opening a worker chat…',
  dispOverCap: 'Waiting for tomorrow: the daily cap is reached.', dispNotDo: 'Not started: decide Do first.', dispNotStarted: 'Not started: {e}',
  dispatching: 'Dispatching {n} card(s)…', dispatched: 'Dispatch: {n} of {total} started', dispatchFailed: 'Could not dispatch: {e}',
  colMetric: 'Metric', colA: 'A (now)', colB: 'B (change)', colVerdict: 'Verdict',
  verdict_better: 'better', verdict_same: 'same', verdict_worse: 'worse', noAb: 'No A/B run yet', showDiff: 'Show the diff',
  pcDone: 'Prompt change applied', pcFailed: 'Not applied: {e}',
  signalsCaption: 'Signals, hottest first', colPain: 'Pain', colPeople: 'People', colMentions: 'Mentions', colDays: 'Days', colSource: 'Source', colLayer: 'Layer',
  layer_real: 'real', layer_external: 'external', mergedInto: 'Merged into {id}',
  refresh: 'Refresh signals', refreshing: 'Refreshing signals…', refreshed: 'Signals: {total} ({added} new)', refreshFailed: 'Could not refresh: {e}',
  ghRunning: 'GitHub: fetching since {at}…', ghNever: 'GitHub: not fetched yet', ghFailed: 'GitHub: failed at {at} ({e})', ghDone: 'GitHub: {n} rows at {at}',
  scorePrs: 'Score PRs', scoreRunning: 'Scoring PRs since {at}…', scoreFailed: 'Scoring failed at {at} ({e})', scoreDone: 'Scored at {at}: {n} PR(s) changed',
  scoreStartFailed: 'Could not start scoring: {e}',
  jobsTitle: 'Jobs', roundArm: 'Run round', roundConfirm: 'Confirm: run round', roundBusy: 'Round running…', cancel: 'Cancel',
  roundRunning: 'Round {n}: running since {at}…', roundNever: 'Round: not run yet', roundFailed: 'Round {n}: failed at {at} ({e})',
  roundDone: 'Round {n}: {p} proposals from {s} signals at {at}', roundStartFailed: 'Could not start the round: {e}',
  regNone: 'Regression: no run yet', regClean: 'Regression @ {sha}: {pass}/{n} pass · no regressions', regBad: 'Regression @ {sha}: {pass}/{n} pass · {bad} regression(s)',
  runsTitle: 'Last scheduled runs', colJob: 'Job', colStarted: 'Started', colEnded: 'Ended', colResult: 'Result', jobRound: 'Weekly round', jobRegress: 'Daily regression',
  runFailed: 'Failed: {e}', runCards: '{cards} cards from {signals} signals', runClean: 'No regressions at {sha}', runRegress: '{n} regression(s) at {sha}',
  save: 'Save', saved: 'Saved', notSaved: 'Not saved: {e}',
  slackTitle: 'Slack', slackSetYes: 'Slack connector set: yes', slackSetNo: 'Slack connector set: no',
  slackOn: 'Slack: on, reading {n} channel(s) over {days} days', slackOff: 'Slack collection is off: pick your Slack connector to turn it on.',
  field_command: 'Command (blank keeps the saved one)', field_args: 'Arguments', field_channels: 'Channel ids', field_window_days: 'Window (days)', field_workspace_url: 'Workspace URL (for links)',
  schedTitle: 'Schedule', schedIntro: 'Off until you switch a job on and save. Each run ends in one notification; nothing posts to Slack, opens a PR or merges.',
  sched_round_enabled: 'Run a design-crew round once a week', sched_regress_enabled: 'Check the regression exams once a day after new merges',
  sched_score_enabled: 'Score linked KiroCrew PRs with the judge every hour (never runs fork PRs)',
  schedDay: 'Day', schedHour: 'Hour (0-23, local)', schedDir: 'KiroCrew clone for the regression check (absolute path)',
  days: 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
  dispTitle: 'Auto-dispatch', dispToggle: 'Open a worker chat when I press Do',
  dispIntro: 'Off until you switch it on and save. When on, Do on a proposal card opens one worker chat that builds it as one small PR, CI green, never merged. Prompt-change cards never dispatch.',
  dispRepos: 'Target repos (allowlist)', dispCap: 'Dispatches a day (1-10)',
  dispTrust: 'Start each worker chat in Trust',
  dispTrustRisk: 'Risk: a trusted chat runs tools without asking you, including shell and git. Off by default. Every worker chat goes in the Harness RSI folder either way.',
  tab_team: 'Team', teamNote: 'Pushed by the lead and its lanes at the end of each patrol cycle. Self-reported: the app cannot check who sent it. Approvals and credits are not shown.',
  noTeam: 'No team snapshots yet', teamHint: 'The lead and lane agents this app ships push their work ledgers here each patrol cycle.',
  needsTitle: 'Needs you', noNeeds: 'Nothing needs you', need_question: 'Question', need_blocked: 'Blocked', need_merge: 'Ready to merge',
  prNum: 'PR #{n}', openSession: 'Open session', treeTitle: 'Lead and lanes', looseTitle: 'Lanes no lead names', roleLead: 'Lead', roleLane: 'Lane',
  pushedAt: 'Round {round} · pushed {at}', pushedNoRound: 'Pushed {at}', staleReporter: 'No push for over {m} min', orphaned: 'Orphaned', staleItem: 'Stale',
  count_progress: '{n} in progress', count_done: '{n} done', count_blocked: '{n} blocked', count_question: '{n} asking', count_none: '{n} not started',
  count_accepted: '{n} accepted', count_rejected: '{n} rejected', count_abandoned: '{n} abandoned',
  status_progress: 'in progress', status_done: 'done', status_blocked: 'blocked', status_question: 'asking', status_none: 'not started',
  istate_accepted: 'accepted', istate_rejected: 'rejected', istate_abandoned: 'abandoned',
  wverdict_pass: 'pass', wverdict_fail: 'fail', wverdict_pending: 'pending', wverdict_refused: 'refused', wverdict_error: 'error',
  // UX v2 mockup (ui/v2.mjs, docs/design/ux-v2.md)
  v2_subtitle: 'Is it running, what needs you, and how your picks are doing.',
  v2_demoNote: 'UX v2 mockup on sample data. Nothing is saved. Remove &ux=v2 for the current page.',
  v2_view_home: 'Home', v2_view_needs: 'Needs you', v2_view_work: 'Work', v2_view_settings: 'Settings',
  v2_src: 'Source:', v2_on: 'on', v2_off: 'off', v2_gap: 'Not tracked yet', v2_openChat: 'Open chat',
  v2_statusTitle: 'Is it running?', v2_idle: 'Idle: no round is running.', v2_running: 'Running round {n}, since {at}.',
  v2_last: 'Last round {n}: {s} signals → {p} cards, ended {at}.', v2_lastFailed: 'Last round {n} failed at {at}: {e}', v2_lastNever: 'No round has run yet.',
  v2_next: 'Next round: {when}.', v2_nextAt: 'every {day} at {hour}:00 (gateway clock)', v2_schedOff: 'schedule is off',
  v2_sw_round_enabled: 'Weekly round: {on}', v2_sw_regress_enabled: 'Daily regress: {on}', v2_sw_score_enabled: 'PR scoring: {on}',
  v2_setupTitle: 'Setup: {done} of {n} done', v2_stepDone: 'Done', v2_stepOpen: 'To do',
  v2_step_slack: 'Connect Slack (a source of signals)', v2_step_dir: 'Set the KiroCrew checkout (runs exams)',
  v2_step_repos: 'Name the repo fixes go to', v2_step_sched: 'Turn on the weekly round',
  v2_actTitle: 'Act now', v2_do_slack: 'Set up Slack', v2_do_dir: 'Set the KiroCrew checkout', v2_do_repos: 'Name the target repo', v2_do_sched: 'Turn on the schedule',
  v2_goNeeds: 'Handle what needs you ({n})',
  v2_costSetup: 'Opens Settings. Free; nothing runs.', v2_costNeeds: 'Opens the queue. Free; nothing runs.',
  v2_costRound: 'Runs the design crew now: about an hour, uses model credits, makes cards only, never a PR.',
  v2_detailsTitle: 'Details: signals, runs, raw A/B', v2_detailsSignals: 'Every signal the last refresh read.', v2_rawAb: 'Raw A/B: {agent}',
  v2_needsNote: 'One queue. Each item says why it is here, the evidence, and one action.',
  v2_needsEmpty: 'Nothing needs you', v2_needsEmptyNext: 'Next round: {when}.',
  v2_kind_pick: 'Pick', v2_kind_start: 'Start', v2_kind_prompt: 'Prompt change', v2_kind_question: 'Question', v2_kind_blocked: 'Blocked', v2_kind_merge: 'Merge',
  v2_why_pick: 'A new card from the last round. No decision yet.', v2_why_start: 'You chose Do. No worker chat is open yet.',
  v2_why_prompt: 'The crew proposes a new prompt. It only applies when you say so.',
  v2_why_question: 'A worker chat asks you something (self-reported).', v2_why_blocked: 'A worker chat is stuck (self-reported).',
  v2_why_merge: 'The PR is done and accepted. Only you merge.',
  v2_actPick: 'Do this', v2_costPick: 'Moves it to Work. Starts nothing.',
  v2_actStart: 'Start a worker chat', v2_costStart: 'Opens 1 chat that makes 1 PR and never merges. {left} left today.',
  v2_abFrom: 'A/B: offline replay of rounds {rounds}, {reps} runs each, by', v2_proposedAt: 'proposed {at}',
  v2_actApply: 'Switch to B', v2_costApply: 'Writes a new {agent} prompt version. Next round uses it.',
  v2_actOpenPr: 'Open PR #{n}', v2_costMerge: 'Merge on GitHub; this app never merges.', v2_costChat: 'Opens the chat. Answer there.',
  v2_workNote: 'One row per card you chose, from pick to merge to score.',
  v2_workEmpty: 'Nothing in progress', v2_workEmptyNext: 'Next step: pick a card in Needs you.',
  v2_ws_picked: 'Picked', v2_ws_chat: 'Chat', v2_ws_pr: 'PR', v2_ws_ci: 'CI', v2_ws_merged: 'Merged', v2_ws_judge: 'Score',
  v2_noCard: 'No card', v2_noCardPr: 'PR #{n} (no card)', v2_ciGap: 'CI is not tracked yet: the backend does not read PR checks.',
  v2_setNote: 'Mockup: shows state only. Change settings on the current page.',
  v2_setSources: 'Sources', v2_setSchedule: 'Schedule', v2_setTrust: 'Trust', v2_setCaps: 'Caps',
  v2_set_slack: 'Slack', v2_set_github: 'GitHub issues', v2_set_sessions: 'Chat history',
  v2_set_round: 'Weekly round', v2_set_regress: 'Daily regress', v2_set_score: 'PR scoring', v2_set_dir: 'KiroCrew checkout',
  v2_set_trust: 'Worker chats start in Trust', v2_set_cap: 'Daily dispatch cap', v2_set_repos: 'Target repos', v2_set_auto: 'Auto-dispatch on Do',
  v2_connected: 'Connected', v2_notSet: 'Not set', v2_neverRead: 'Never read',
  v2_howSlack: 'Pick your Slack connector and channels.', v2_howGithub: 'Read on Refresh, from the repos in Settings.',
  v2_howSessions: 'No switch or state yet.', v2_howRegress: 'Reruns merged exams once a day.', v2_howScore: 'Scores linked PRs on the hourly tick.',
  v2_howDir: 'A local KiroCrew clone. Without it exams do not run.', v2_howCap: 'Most worker chats per day.',
  v2_howRepos: 'The only repos a worker may open a PR on.', v2_howAuto: 'Off: Do starts nothing until you press Start.',
  v2_notePicked: 'Picked. It is in Work now.', v2_noteStarted: 'Worker chat started. See Work.', v2_noteNotStarted: 'Not started. See the card in Work.',
  v2_noteApplied: 'Switched to B (demo: nothing saved).', v2_noteRound: 'Round started (demo: nothing runs).',
  tab_home: 'Home',
  jobManual: 'Manual round',
  noRunsHint: 'Next: run a round below, or turn on the weekly round in Settings.',
  // Needs you tab (ui/needs.mjs)
  tab_needs: 'Needs you',
  needs_note: '{n} thing(s) wait on you. Each says why, the evidence, and one action.',
  needs_empty: 'Nothing needs you',
  needs_kind_pick: 'Pick',
  needs_kind_start: 'Start',
  needs_kind_prompt: 'Prompt change',
  needs_kind_question: 'Question',
  needs_kind_blocked: 'Blocked',
  needs_kind_merge: 'Merge',
  needs_why_pick: 'A new card from a round. No decision yet.',
  needs_why_start: 'You chose Do. No worker chat is open for it yet.',
  needs_why_prompt: 'The crew proposes a new prompt. It applies only when you say so.',
  needs_why_question: 'A worker chat asks you something (self-reported).',
  needs_why_blocked: 'A worker chat is stuck (self-reported).',
  needs_why_merge: 'The PR is done and passed its check (self-reported). Only you merge.',
  needs_doesPick: 'Saves your choice.',
  needs_actStart: 'Start worker chat',
  needs_doesStart: 'Opens 1 chat that makes 1 PR and never merges. {left} left today.',
  needs_doesStartUnknown: 'Opens 1 chat that makes 1 PR and never merges.',
  needs_lastFailed: 'Last try failed at {at}: {e}',
  needs_abFrom: 'A/B: offline replay of rounds {rounds}, {reps} runs each;',
  needs_abRan: 'ran {at} with',
  needs_abRanUnknown: 'run time not recorded; script',
  needs_proposed: 'Proposed {at}.',
  needs_actApply: 'Switch to B',
  needs_doesApply: 'Writes a new {agent} prompt version. The next round uses it.',
  needs_reported: 'Reported by {who}, {at}.',
  needs_actOpenPr: 'Open PR #{n}',
  needs_doesMerge: 'Merge on GitHub; this app never merges.',
  needs_doesChat: 'Answer in the chat.',
  home_src: 'Source:',
  home_on: 'on',
  home_off: 'off',
  home_unread: 'Not read yet.',
  home_min: '{m} min',
  home_hm: '{h} h {m} min',
  home_statusTitle: 'Is it running?',
  home_idle: 'Idle: no round is running.',
  home_running: 'Running round {n}, since {at}.',
  home_last: 'Last round: {s} signals → {p} cards, ended {at}.',
  home_lastFailed: 'Last round failed at {at}: {e}',
  home_lastNever: 'No round has run yet. Next: Run round below.',
  home_next: 'Next round: {at} (the first hourly check after it starts it).',
  home_nextDue: 'Next round: due now; the next hourly check starts it.',
  home_nextOff: 'Next round: none, the weekly round is off. Turn it on in Settings.',
  home_sw_round_enabled: 'Weekly round: {on}',
  home_sw_regress_enabled: 'Daily regress: {on}',
  home_sw_score_enabled: 'PR scoring: {on}',
  home_setupTitle: 'Setup: {done} of {n} done',
  home_stepDone: 'Done',
  home_stepOpen: 'To do',
  home_step_slack: 'Slack (a source of signals)',
  home_step_github: 'GitHub issues (a source of signals)',
  home_step_chats: 'Your chat history (a source of signals)',
  home_step_schedule: 'Weekly schedule',
  home_step_trust: 'Trust for worker chats',
  // SRC-A: the Slack connector picker and the GitHub repo list on Settings.
  srcA_pickLabel: 'Which Slack connector to use',
  srcA_pickHelp: 'The app reads Slack through an MCP server you already use; it has no Slack token.',
  srcA_pickChoose: 'Choose one…',
  srcA_pickKeep: 'Keep the current one',
  srcA_from_user: '{name} (your settings)',
  srcA_from_workspace: '{name} (this workspace)',
  srcA_pickAdvanced: 'Advanced: type the command',
  srcA_pickNone: 'No Slack connector found in your mcp.json. Add one there, or use Advanced.',
  srcA_pickUnusable: 'Found but not usable here (spaces or shell syntax in its command): {names}. Use Advanced.',
  srcA_advancedHelp: 'Only if your connector is not in the list. Words only, no spaces or shell syntax.',
  srcA_slackUsing: 'Slack connector: {name}',
  srcA_ghTitle: 'GitHub issues',
  srcA_ghIntro: 'Each refresh and each round reads the open issues of these repos.',
  srcA_ghRepos: 'Repos (owner/name, comma separated, up to 10)',
  srcA_ghNever: 'not read yet',
  srcA_ghFailed: 'failed at {at} ({e})',
  srcA_ghRead: '{n} issue(s) at {at}',
  srcA_ghOff: 'No repo set: GitHub is not read.',
  srcA_homeGhOff: 'Off: no GitHub repo is set. Add one in Settings.',
  home_slackNo: 'Not set: pick your Slack connector in Settings.',
  home_ghRows: '{n} signals from GitHub so far.',
  home_ghNo: 'Never read. Next: Refresh on the Signals tab.',
  home_chatsRows: '{n} signals from your chats so far.',
  home_chatsErr: 'The last round could not read your chats ({e}).',
  home_chatsNo: 'Not read yet. Next: Run round below; each round reads your chats. No setting needed.',
  home_schedOff: 'Off: the weekly round does not run. Turn it on in Settings.',
  home_schedNoDir: 'On, but no KiroCrew clone is set, so exams do not run. Set it in Settings.',
  home_trustOff: 'Off: worker chats ask you before running tools.',
  home_fixSettings: 'Fix in Settings',
  home_actTitle: 'Act now',
  home_roundDoes: 'Run round: the design crew reads Slack, GitHub and your chats, then makes cards to pick from. It never opens a PR. Uses model credits.',
  home_costAvg: 'Last {n} round(s) took {d} on average; cost: {c}.',
  home_costUnknown: 'unknown (not measured yet)',
  home_credits: '{c} credits',
  home_costNone: 'Time and cost: unknown until a round finishes.',
  home_detailsTitle: 'Details: signals, runs, raw A/B',
  home_detailsSignals: 'Every signal the last refresh or round read.',
  home_rawAb: 'Raw A/B: {agent}',
  home_abFrom: 'A/B: offline replay of rounds {rounds}, {reps} runs each, by',
  home_proposedAt: 'proposed {at}',
  home_noAb: 'No A/B yet. A prompt change brings one.',
  // Work tab (ui/work.mjs)
  tab_work: 'Work',
  work_note: 'One row per card you picked, from pick to merge to score. CI is the check rollup of the PR head.',
  work_flagsNote: 'Flags and notes are what the crew reported (self-reported).',
  work_ciError: 'CI not read just now: {e}. Showing the last read.',
  work_empty: 'Nothing in progress',
  work_emptyNext: 'Next step: pick a card with Do in Needs you.',
  work_step_picked: 'Picked', work_step_chat: 'Chat', work_step_pr: 'PR', work_step_ci: 'CI', work_step_merged: 'Merged', work_step_judge: 'Score',
  work_noCard: 'No card',
  work_noCardPr: 'PR #{n} (no card)',
  work_lostCard: 'PR #{n} (card {id}, no longer listed)',
  work_openChat: 'Open chat',
  work_chatFailed: 'Not started',
  work_ci_pass: 'pass', work_ci_fail: 'fail', work_ci_pending: 'running', work_ci_none: 'no checks', work_ci_unknown: 'not read yet',
  work_flag_blocked: 'Blocked', work_flag_question: 'Asks you', work_flag_stale: 'Stale', work_flag_orphaned: 'Orphaned', work_flag_failed: 'Dispatch failed',
  work_said: 'Crew says: {s}',
}

const zh = {
  title: 'Harness 自我改进', subtitle: '选出下一步要做的事。你决定之前，什么都不会运行。',
  demoNote: '演示模式：显示示例数据，不会保存任何内容。去掉地址里的 ?demo=1 即可看到你的数据。',
  tabsAria: 'Harness 自我改进的分区', tab_settings: '设置',
  statProposals: '提案', statPending: '等你决定', statSignals: '信号', statPrompts: '提示词改动',
  loadFailed: '无法加载数据', emptyHint: '运行一轮，或用 ?demo=1 打开本页预览示例数据。',
  noSignals: '还没有信号', noRuns: '还没有定时运行记录',
  heat: '{people} 人 / {days} 天', cost: '{files} 个文件 · {lines} 行',
  scoreJudge: '评分：基线 {base} → 新版 {head}', scoreNot: '未评分：{note}', scoreYet: '还没有评分',
  judge_pass: '通过', judge_fail: '未通过', state_merged: '已合并', state_open: '进行中', state_closed: '已关闭',
  regressNotRun: '回归：还没运行', regressLine: '回归 @ {sha}：{pass}/{n} 通过', regressLineBad: '回归 @ {sha}：{pass}/{n} 通过 · {bad} 个回归',
  dec_do: '做', dec_skip: '不做', dec_later: '以后再说',
  savedDecision: '已保存：{d}', decideFailed: '决定没有保存：{e}',
  dispOpening: '正在打开工作对话…', dispChat: '工作对话：{s}',
  savedNotStarted: '已保存。还没开始：到「等你处理」开工作对话，或打开自动派发。',
  dispStarted: '已开始。', dispAlready: '已经派发过。', dispAlreadyOpening: '已经派发过：正在打开工作对话…',
  dispOverCap: '等明天：今天的派发上限已到。', dispNotDo: '还没开始：先选「做」。', dispNotStarted: '还没开始：{e}',
  dispatching: '正在派发 {n} 张卡片…', dispatched: '派发：{total} 张中开始了 {n} 张', dispatchFailed: '没能派发：{e}',
  colMetric: '指标', colA: 'A（现在）', colB: 'B（改动）', colVerdict: '结论',
  verdict_better: '更好', verdict_same: '持平', verdict_worse: '更差', noAb: '还没有 A/B 结果', showDiff: '查看改动',
  pcDone: '提示词改动已应用', pcFailed: '没有应用：{e}',
  signalsCaption: '信号，按热度排序', colPain: '痛点', colPeople: '人数', colMentions: '提及', colDays: '天数', colSource: '来源', colLayer: '类别',
  layer_real: '真实', layer_external: '外部', mergedInto: '已合并到 {id}',
  refresh: '刷新信号', refreshing: '正在刷新信号…', refreshed: '信号：{total} 条（新增 {added}）', refreshFailed: '无法刷新：{e}',
  ghRunning: 'GitHub：{at} 起正在获取…', ghNever: 'GitHub：还没获取', ghFailed: 'GitHub：{at} 失败（{e}）', ghDone: 'GitHub：{at} 获取 {n} 条',
  scorePrs: '给 PR 评分', scoreRunning: '{at} 起正在评分…', scoreFailed: '评分在 {at} 失败（{e}）', scoreDone: '{at} 完成评分：{n} 个 PR 有变化',
  scoreStartFailed: '无法开始评分：{e}',
  jobsTitle: '任务', roundArm: '运行一轮', roundConfirm: '确认：运行一轮', roundBusy: '正在运行…', cancel: '取消',
  roundRunning: '第 {n} 轮：{at} 起运行中…', roundNever: '轮次：还没运行', roundFailed: '第 {n} 轮：{at} 失败（{e}）',
  roundDone: '第 {n} 轮：{at} 从 {s} 条信号得到 {p} 个提案', roundStartFailed: '无法开始这一轮：{e}',
  regNone: '回归：还没运行', regClean: '回归 @ {sha}：{pass}/{n} 通过 · 没有回归', regBad: '回归 @ {sha}：{pass}/{n} 通过 · {bad} 个回归',
  runsTitle: '最近的定时运行', colJob: '任务', colStarted: '开始', colEnded: '结束', colResult: '结果', jobRound: '每周一轮', jobRegress: '每日回归',
  runFailed: '失败：{e}', runCards: '从 {signals} 条信号得到 {cards} 张卡片', runClean: '{sha} 没有回归', runRegress: '{sha} 有 {n} 个回归',
  save: '保存', saved: '已保存', notSaved: '没有保存：{e}',
  slackTitle: 'Slack', slackSetYes: '已选 Slack 连接器：是', slackSetNo: '已选 Slack 连接器：否',
  slackOn: 'Slack：已开启，读取 {n} 个频道最近 {days} 天', slackOff: 'Slack 收集已关闭：选好 Slack 连接器即可开启。',
  field_command: '命令（留空则保留已保存的）', field_args: '参数', field_channels: '频道 ID', field_window_days: '时间窗口（天）', field_workspace_url: '工作区地址（用于链接）',
  schedTitle: '定时', schedIntro: '打开某项并保存之前都不会运行。每次运行只发一条通知；不会发 Slack、开 PR 或合并。',
  sched_round_enabled: '每周运行一轮设计组', sched_regress_enabled: '有新合并后，每天检查一次回归考题',
  sched_score_enabled: '每小时用评分器给关联的 KiroCrew PR 评分（从不运行 fork 的 PR）',
  schedDay: '星期', schedHour: '小时（0-23，本地时间）', schedDir: '用于回归检查的 KiroCrew 目录（绝对路径）',
  days: '星期一,星期二,星期三,星期四,星期五,星期六,星期日',
  dispTitle: '自动派发', dispToggle: '按「做」时打开一个工作对话',
  dispIntro: '打开并保存之前都不会运行。打开后，在提案卡片上按「做」会打开一个工作对话，把它做成一个小 PR，CI 通过，从不合并。提示词改动卡片从不派发。',
  dispRepos: '目标仓库（允许列表）', dispCap: '每天派发上限（1-10）',
  dispTrust: '工作对话一开始就是信任模式',
  dispTrustRisk: '风险：信任模式的对话不问你就运行工具，包括命令行和代码提交。默认关闭。不管开不开，工作对话都放进同一个文件夹。',
  tab_team: '团队', teamNote: '由领队和各分线在每次巡查结束时推送。这是自报数据：本应用无法核实发送者。这里不显示批准和用量。',
  noTeam: '还没有团队快照', teamHint: '本应用带的领队和分线每次巡查都会把工作账本推到这里。',
  needsTitle: '等你处理', noNeeds: '没有要你处理的事', need_question: '提问', need_blocked: '受阻', need_merge: '待你合并',
  prNum: 'PR #{n}', openSession: '打开会话', treeTitle: '领队和分线', looseTitle: '没有领队认领的分线', roleLead: '领队', roleLane: '分线',
  pushedAt: '第 {round} 轮 · {at} 推送', pushedNoRound: '{at} 推送', staleReporter: '超过 {m} 分钟没有推送', orphaned: '无人接手', staleItem: '停滞',
  count_progress: '{n} 进行中', count_done: '{n} 已完成', count_blocked: '{n} 受阻', count_question: '{n} 在提问', count_none: '{n} 未开始',
  count_accepted: '{n} 已验收', count_rejected: '{n} 已拒绝', count_abandoned: '{n} 已放弃',
  status_progress: '进行中', status_done: '已完成', status_blocked: '受阻', status_question: '在提问', status_none: '未开始',
  istate_accepted: '已验收', istate_rejected: '已拒绝', istate_abandoned: '已放弃',
  wverdict_pass: '通过', wverdict_fail: '未通过', wverdict_pending: '待定', wverdict_refused: '被拒', wverdict_error: '出错',
  v2_subtitle: '它在不在跑，什么要你处理，你挑的修复进展如何。',
  v2_demoNote: '界面 v2 样稿，用的是示例数据，什么都不保存。去掉地址里的 &ux=v2 回到现在的页面。',
  v2_view_home: '首页', v2_view_needs: '等你处理', v2_view_work: '进行中', v2_view_settings: '设置',
  v2_src: '来源：', v2_on: '开', v2_off: '关', v2_gap: '还没有记录', v2_openChat: '打开对话',
  v2_statusTitle: '在不在跑？', v2_idle: '空闲：没有在跑的轮次。', v2_running: '正在跑第 {n} 轮，从 {at} 开始。',
  v2_last: '上一轮第 {n} 轮：{s} 个信号 → {p} 张卡片，{at} 结束。', v2_lastFailed: '上一轮第 {n} 轮在 {at} 失败：{e}', v2_lastNever: '还没跑过轮次。',
  v2_next: '下一轮：{when}。', v2_nextAt: '每{day} {hour}:00（网关时间）', v2_schedOff: '计划已关闭',
  v2_sw_round_enabled: '每周轮次：{on}', v2_sw_regress_enabled: '每日回归：{on}', v2_sw_score_enabled: 'PR 评分：{on}',
  v2_setupTitle: '设置：完成 {done} / {n}', v2_stepDone: '已完成', v2_stepOpen: '待完成',
  v2_step_slack: '接上 Slack（信号来源之一）', v2_step_dir: '设置 KiroCrew 目录（用来跑考题）',
  v2_step_repos: '填写修复要提交到的仓库', v2_step_sched: '打开每周轮次',
  v2_actTitle: '马上行动', v2_do_slack: '设置 Slack', v2_do_dir: '设置 KiroCrew 目录', v2_do_repos: '填写目标仓库', v2_do_sched: '打开计划',
  v2_goNeeds: '去处理（{n}）',
  v2_costSetup: '打开设置。不花钱，不运行任何东西。', v2_costNeeds: '打开队列。不花钱，不运行任何东西。',
  v2_costRound: '马上让设计组跑一轮：大约一小时，花模型额度，只出卡片，从不出 PR。',
  v2_detailsTitle: '明细：信号、运行记录、原始 A/B', v2_detailsSignals: '上次刷新读到的全部信号。', v2_rawAb: '原始 A/B：{agent}',
  v2_needsNote: '一条队列。每条写清为什么在这、证据、一个按钮。',
  v2_needsEmpty: '没有要你处理的事', v2_needsEmptyNext: '下一轮：{when}。',
  v2_kind_pick: '挑选', v2_kind_start: '开工', v2_kind_prompt: '提示词改动', v2_kind_question: '提问', v2_kind_blocked: '受阻', v2_kind_merge: '合并',
  v2_why_pick: '上一轮的新卡片，还没决定。', v2_why_start: '你选了「做」，还没开工作对话。',
  v2_why_prompt: '设计组提议换一版提示词。你同意才生效。',
  v2_why_question: '有工作对话在问你（自报）。', v2_why_blocked: '有工作对话卡住了（自报）。',
  v2_why_merge: 'PR 做完并验收了。只有你能合并。',
  v2_actPick: '做这个', v2_costPick: '移到进行中。不会开始任何东西。',
  v2_actStart: '开工作对话', v2_costStart: '打开 1 个对话，做 1 个 PR，从不合并。今天还能开 {left} 个。',
  v2_abFrom: 'A/B：离线重放第 {rounds} 轮，各跑 {reps} 次，脚本', v2_proposedAt: '{at} 提议',
  v2_actApply: '换成 B', v2_costApply: '给 {agent} 写一个新提示词版本，下一轮起生效。',
  v2_actOpenPr: '打开 PR #{n}', v2_costMerge: '在 GitHub 上合并；本应用从不合并。', v2_costChat: '打开对话，在那里回答。',
  v2_workNote: '你选的每张卡片一行，从挑选到合并到评分。',
  v2_workEmpty: '还没有在做的', v2_workEmptyNext: '下一步：去「等你处理」挑一张卡片。',
  v2_ws_picked: '已选', v2_ws_chat: '对话', v2_ws_pr: 'PR', v2_ws_ci: 'CI', v2_ws_merged: '已合并', v2_ws_judge: '评分',
  v2_noCard: '没有卡片', v2_noCardPr: 'PR #{n}（没有卡片）', v2_ciGap: '还没记录 CI：后端不读 PR 的检查结果。',
  v2_setNote: '样稿：只显示状态。改设置请用现在的页面。',
  v2_setSources: '来源', v2_setSchedule: '计划', v2_setTrust: '信任', v2_setCaps: '名额',
  v2_set_slack: 'Slack', v2_set_github: 'GitHub 问题', v2_set_sessions: '对话记录',
  v2_set_round: '每周轮次', v2_set_regress: '每日回归', v2_set_score: 'PR 评分', v2_set_dir: 'KiroCrew 目录',
  v2_set_trust: '工作对话一开始就是信任模式', v2_set_cap: '每天派发上限', v2_set_repos: '目标仓库', v2_set_auto: '选「做」后自动派发',
  v2_connected: '已接上', v2_notSet: '没设置', v2_neverRead: '从没读过',
  v2_howSlack: '选好 Slack 连接器和频道。', v2_howGithub: '点刷新时读取设置里的仓库。',
  v2_howSessions: '还没有开关和状态。', v2_howRegress: '每天把合并过的考题再跑一遍。', v2_howScore: '每小时给关联的 PR 评分。',
  v2_howDir: '本机的 KiroCrew 副本。没有它考题跑不了。', v2_howCap: '每天最多开几个工作对话。',
  v2_howRepos: '工作对话只能在这些仓库开 PR。', v2_howAuto: '关：选「做」不会开始，要你按「开工作对话」。',
  v2_notePicked: '已选。它现在在「进行中」。', v2_noteStarted: '工作对话已开。见「进行中」。', v2_noteNotStarted: '没开成。见「进行中」里的卡片。',
  v2_noteApplied: '已换成 B（样稿：没有保存）。', v2_noteRound: '已开始一轮（样稿：什么都不运行）。',
  tab_home: '首页',
  jobManual: '手动一轮',
  noRunsHint: '下一步：在下面运行一轮，或在设置里打开每周一轮。',
  // 等你处理（ui/needs.mjs）
  tab_needs: '等你处理',
  needs_note: '有 {n} 件事等你。每件写了为什么、证据和一个按钮。',
  needs_empty: '没有要你处理的事',
  needs_kind_pick: '挑一个',
  needs_kind_start: '开工作对话',
  needs_kind_prompt: '提示词改动',
  needs_kind_question: '提问',
  needs_kind_blocked: '受阻',
  needs_kind_merge: '合并',
  needs_why_pick: '一轮做出的新卡片，还没决定。',
  needs_why_start: '你选了「做」，还没开工作对话。',
  needs_why_prompt: '小组提了一份新提示词。你点了才会换上。',
  needs_why_question: '一个工作对话在问你（自报）。',
  needs_why_blocked: '一个工作对话卡住了（自报）。',
  needs_why_merge: 'PR 做完了，也验过了（自报）。只有你能合并。',
  needs_doesPick: '保存你的选择。',
  needs_actStart: '开工作对话',
  needs_doesStart: '开 1 个对话，做 1 个 PR，从不合并。今天还能开 {left} 个。',
  needs_doesStartUnknown: '开 1 个对话，做 1 个 PR，从不合并。',
  needs_lastFailed: '上次 {at} 没开成：{e}',
  needs_abFrom: 'A/B：离线重放第 {rounds} 轮，各 {reps} 次；',
  needs_abRan: '{at} 跑的，命令',
  needs_abRanUnknown: '没记下跑的时间；脚本',
  needs_proposed: '{at} 提议。',
  needs_actApply: '换成 B',
  needs_doesApply: '给 {agent} 写一个新提示词版本，下一轮就用它。',
  needs_reported: '{who} 在 {at} 报的。',
  needs_actOpenPr: '打开 PR #{n}',
  needs_doesMerge: '在 GitHub 上合并；这个应用从不合并。',
  needs_doesChat: '去对话里回答。',
  home_src: '来源：',
  home_on: '开',
  home_off: '关',
  home_unread: '还没读到。',
  home_min: '{m} 分钟',
  home_hm: '{h} 小时 {m} 分钟',
  home_statusTitle: '在不在跑？',
  home_idle: '空闲：没有在跑的轮次。',
  home_running: '正在跑第 {n} 轮，从 {at} 开始。',
  home_last: '上一轮：{s} 个信号 → {p} 张卡，{at} 结束。',
  home_lastFailed: '上一轮 {at} 失败：{e}',
  home_lastNever: '还没跑过。下一步：点下面的「运行一轮」。',
  home_next: '下一轮：{at}（之后第一次整点检查时开始）。',
  home_nextDue: '下一轮：已到时间，下一次整点检查时开始。',
  home_nextOff: '下一轮：没有，每周一轮是关的。在设置里打开。',
  home_sw_round_enabled: '每周一轮：{on}',
  home_sw_regress_enabled: '每日回归：{on}',
  home_sw_score_enabled: 'PR 评分：{on}',
  home_setupTitle: '设置：{n} 项做完 {done} 项',
  home_stepDone: '已做',
  home_stepOpen: '待做',
  home_step_slack: 'Slack（信号来源）',
  home_step_github: 'GitHub 问题（信号来源）',
  home_step_chats: '你的对话记录（信号来源）',
  home_step_schedule: '每周计划',
  home_step_trust: '工作对话的信任模式',
  // SRC-A：设置页的 Slack 连接器选择和 GitHub 仓库列表。
  srcA_pickLabel: '用哪个 Slack 连接器',
  srcA_pickHelp: '本应用通过你已在用的 MCP 服务器读 Slack；它自己没有 Slack 令牌。',
  srcA_pickChoose: '选一个…',
  srcA_pickKeep: '保持当前的',
  srcA_from_user: '{name}（你的设置）',
  srcA_from_workspace: '{name}（本工作区）',
  srcA_pickAdvanced: '高级：手动填写命令',
  srcA_pickNone: '在你的 MCP 配置文件里没找到 Slack 连接器。先在那里加一个，或用“高级”。',
  srcA_pickUnusable: '找到了但这里用不了（命令里有空格或特殊符号）：{names}。请用“高级”。',
  srcA_advancedHelp: '只在列表里没有你的连接器时使用。只能是单词，不能有空格或特殊符号。',
  srcA_slackUsing: 'Slack 连接器：{name}',
  srcA_ghTitle: 'GitHub 问题',
  srcA_ghIntro: '每次刷新和每一轮都会读这些仓库里未关闭的问题。',
  srcA_ghRepos: '仓库（所有者/名称，用逗号分隔，最多 10 个）',
  srcA_ghNever: '还没读过',
  srcA_ghFailed: '{at} 失败（{e}）',
  srcA_ghRead: '{at} 读到 {n} 个问题',
  srcA_ghOff: '没有设置仓库：不读 GitHub。',
  srcA_homeGhOff: '关闭：没有设置 GitHub 仓库。到设置里加一个。',
  home_slackNo: '没设置：在设置里选好 Slack 连接器。',
  home_ghRows: '目前有 {n} 个信号来自 GitHub。',
  home_ghNo: '还没读过。下一步：在「信号」页点刷新。',
  home_chatsRows: '目前有 {n} 个信号来自你的对话。',
  home_chatsErr: '上一轮没读到你的对话（{e}）。',
  home_chatsNo: '还没读过。下一步：点下面的「运行一轮」，每轮都会读你的对话。不用设置。',
  home_schedOff: '关：每周一轮不会跑。在设置里打开。',
  home_schedNoDir: '开了，但没设 KiroCrew 副本，考题跑不了。在设置里填上。',
  home_trustOff: '关：工作对话运行工具前会先问你。',
  home_fixSettings: '去设置里改',
  home_actTitle: '现在做',
  home_roundDoes: '运行一轮：设计小组读 Slack、GitHub 和你的对话，做出卡片让你挑。从不开 PR。花模型额度。',
  home_costAvg: '最近 {n} 轮平均用时 {d}；花费：{c}。',
  home_costUnknown: '不知道（还没记录）',
  home_credits: '{c} 点额度',
  home_costNone: '用时和花费：跑完一轮之前不知道。',
  home_detailsTitle: '明细：信号、运行记录、原始 A/B',
  home_detailsSignals: '上次刷新或上一轮读到的所有信号。',
  home_rawAb: '原始 A/B：{agent}',
  home_abFrom: 'A/B：离线重放第 {rounds} 轮，各 {reps} 次，脚本',
  home_proposedAt: '{at} 提议',
  home_noAb: '还没有 A/B。提示词改动会带上一份。',
  // 进行中（ui/work.mjs）
  tab_work: '进行中',
  work_note: '你挑的每张卡片一行，从挑选到合并到评分。CI 是 PR 最新提交的检查汇总。',
  work_flagsNote: '标记和说明来自小组自报。',
  work_ciError: '这次没读到 CI：{e}。显示上次读到的。',
  work_empty: '还没有在做的',
  work_emptyNext: '下一步：到「等你处理」给一张卡片选「做」。',
  work_step_picked: '已选', work_step_chat: '对话', work_step_pr: 'PR', work_step_ci: 'CI', work_step_merged: '已合并', work_step_judge: '评分',
  work_noCard: '没有卡片',
  work_noCardPr: 'PR #{n}（没有卡片）',
  work_lostCard: 'PR #{n}（卡片 {id} 已不在列表里）',
  work_openChat: '打开对话',
  work_chatFailed: '没开成',
  work_ci_pass: '通过', work_ci_fail: '没通过', work_ci_pending: '在跑', work_ci_none: '没有检查', work_ci_unknown: '还没读',
  work_flag_blocked: '受阻', work_flag_question: '在问你', work_flag_stale: '没更新', work_flag_orphaned: '没人管', work_flag_failed: '派发失败',
  work_said: '小组说：{s}',
}

export const TABLE = { en, zh }
let lang = 'en'
/** zh for any Chinese host locale, else en. */
export const pickLang = (locale) => (String(locale || '').toLowerCase().startsWith('zh') ? 'zh' : 'en')
export const setLang = (l) => { lang = TABLE[l] ? l : 'en' }
export const getLang = () => lang
export const has = (key) => key in en
/** The string for `key` in the page's language; a key missing from the table is a bug, so it throws. */
export function t(key, vars = {}) {
  const s = TABLE[lang][key]
  if (s == null) throw new Error(`no string for ${key}`)
  return s.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''))
}
